import type { QuizQuestion } from "@/types/quiz";

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "budget",
    text: "What's your monthly housing budget?",
    description: "This helps us filter cities that match your affordability needs.",
    type: "slider",
    range: {
      min: 500,
      max: 4000,
      step: 100,
      labels: ["$500/mo", "$4,000/mo"],
      formatValue: (v: number) => `$${v.toLocaleString()}/mo`,
    },
    affectsCategories: ["costOfLiving", "housing"],
  },
  {
    id: "climate",
    text: "What climate do you prefer?",
    description: "We all have a comfort zone — what's yours?",
    type: "single-select",
    options: [
      { value: "hot-sunny", label: "Hot & sunny year-round" },
      { value: "mild-temperate", label: "Mild & temperate" },
      { value: "four-seasons", label: "Four distinct seasons" },
      { value: "cool-rainy", label: "Cool & rainy" },
    ],
    affectsCategories: ["weather"],
  },
  {
    id: "career",
    text: "What industry do you work in?",
    description: "Helps us match you with cities strong in your field.",
    type: "single-select",
    options: [
      { value: "tech", label: "Technology" },
      { value: "healthcare", label: "Healthcare" },
      { value: "finance", label: "Finance & Business" },
      { value: "remote", label: "Remote / Freelance" },
    ],
    affectsCategories: ["jobMarket"],
  },
  {
    id: "commute",
    text: "How do you prefer to get around?",
    description: "Your daily commute matters more than you think.",
    type: "single-select",
    options: [
      { value: "drive", label: "I'll drive" },
      { value: "transit", label: "Public transit" },
      { value: "walk-bike", label: "Walk or bike" },
      { value: "remote-commute", label: "I work from home" },
    ],
    affectsCategories: ["walkability", "transit"],
  },
  {
    id: "household",
    text: "What's your household situation?",
    description: "Different life stages have different city needs.",
    type: "single-select",
    options: [
      { value: "single", label: "Single" },
      { value: "couple", label: "Couple, no kids" },
      { value: "family", label: "Family with kids" },
      { value: "retiree", label: "Retiree" },
    ],
    affectsCategories: ["education", "safety", "healthcare"],
  },
  {
    id: "nightlife-importance",
    text: "How important is a vibrant nightlife and food scene?",
    description: "From quiet suburbs to bustling downtown — where do you fit?",
    type: "slider",
    range: {
      min: 1,
      max: 5,
      step: 1,
      labels: ["Not important", "Very important"],
    },
    affectsCategories: ["nightlife"],
  },
  {
    id: "safety-priority",
    text: "How important is a low crime rate to you?",
    description: "Safety means different things to different people.",
    type: "slider",
    range: {
      min: 1,
      max: 5,
      step: 1,
      labels: ["Less concerned", "Top priority"],
    },
    affectsCategories: ["safety"],
  },
  {
    id: "city-size",
    text: "What size city appeals to you?",
    description: "Big-city energy or small-town charm?",
    type: "single-select",
    options: [
      { value: "major", label: "Major metro (1M+)" },
      { value: "midsize", label: "Mid-size (250K - 1M)" },
      { value: "smaller", label: "Smaller city (under 250K)" },
    ],
    affectsCategories: [],
  },
  {
    id: "must-haves",
    text: "Select any must-haves for your ideal city.",
    description: "Pick all that apply — these become hard filters.",
    type: "multi-select",
    options: [
      { value: "affordable", label: "Affordable housing" },
      { value: "good-schools", label: "Good public schools" },
      { value: "walkable", label: "Walkable neighborhoods" },
      { value: "outdoor-recreation", label: "Outdoor recreation nearby" },
    ],
    affectsCategories: ["costOfLiving", "education", "walkability"],
  },
];
